#!/bin/bash

if ! [ -f "$HOME/.profile" ] || ! [ -f "$HOME/.bash_profile" ];
then
  curl -fLoSs "https://raw.githubusercontent.com/nrobinson2000/bashrc/master/.bash_profile" "$HOME/.bash_profile"
fi

if ! [ -f "$HOME/.bashrc" ];
then
  curl -fLoSs "https://raw.githubusercontent.com/nrobinson2000/bashrc/master/.bashrc" "$HOME/.bashrc"
else
  curl -fLSs "https://raw.githubusercontent.com/nrobinson2000/bashrc/master/.bashrc" >> "$HOME/.bashrc"
fi
