#!/bin/bash
echo
echo "Installing .bashrc..."

if ! ( [ -f "$HOME/.profile" ] || [ -f "$HOME/.bash_profile" ] );
then
  curl -fLSso "https://raw.githubusercontent.com/nrobinson2000/bashrc/master/.bash_profile" "$HOME/.bash_profile"
fi

if ! [ -f "$HOME/.bashrc" ];
then
  curl -fLSso "https://raw.githubusercontent.com/nrobinson2000/bashrc/master/.bashrc" "$HOME/.bashrc"
else
  curl -L "https://raw.githubusercontent.com/nrobinson2000/bashrc/master/.bashrc" >> "$HOME/.bashrc"
fi

echo
